import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
}

// ---------------------------------------------------------------------------------------------
// Build-time config (Supabase project + AI). Read from local.properties or environment variables,
// generated into a Kotlin object so common code can use it on every platform. Empty values mean
// "cloud off": the app runs fully local, exactly like the MVP.
//
//   local.properties:  supabase.url=https://xyzcompany.supabase.co
//                      supabase.anonKey=eyJhbGciOi...
// ---------------------------------------------------------------------------------------------
val localProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}
fun configValue(prop: String, env: String): String =
    (localProps.getProperty(prop) ?: System.getenv(env) ?: "").trim()

val supabaseUrl = configValue("supabase.url", "GOLDENPAW_SUPABASE_URL")
val supabaseAnonKey = configValue("supabase.anonKey", "GOLDENPAW_SUPABASE_ANON_KEY")
val appVersionName = providers.gradleProperty("goldenpaw.versionName").getOrElse("1.0.0")
val appVersionCode = providers.gradleProperty("goldenpaw.versionCode").getOrElse("1")

val generateAppConfig by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/appconfig/commonMain/kotlin")
    val url = supabaseUrl
    val key = supabaseAnonKey
    val versionName = appVersionName
    val versionCode = appVersionCode
    inputs.property("url", url)
    inputs.property("key", key)
    inputs.property("versionName", versionName)
    inputs.property("versionCode", versionCode)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("com/goldenpaw/config/AppConfig.kt").asFile
        file.parentFile.mkdirs()
        fun esc(s: String) = s.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
        file.writeText(
            """
            |// Generated by :shared:generateAppConfig. Do not edit.
            |package com.goldenpaw.config
            |
            |object AppConfig {
            |    const val VERSION_NAME: String = "${esc(versionName)}"
            |    const val VERSION_CODE: Int = $versionCode
            |    const val SUPABASE_URL: String = "${esc(url)}"
            |    const val SUPABASE_ANON_KEY: String = "${esc(key)}"
            |    val isCloudConfigured: Boolean get() = SUPABASE_URL.isNotBlank() && SUPABASE_ANON_KEY.isNotBlank()
            |}
            """.trimMargin() + "\n",
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }
    jvm("desktop") {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    sourceSets {
        all {
            languageSettings.optIn("kotlin.uuid.ExperimentalUuidApi")
            languageSettings.optIn("kotlinx.coroutines.ExperimentalCoroutinesApi")
        }
        commonMain {
            kotlin.srcDir(generateAppConfig)
            dependencies {
                api(libs.kotlinx.coroutines.core)
                api(libs.kotlinx.datetime)
                implementation(libs.kotlinx.serialization.json)
                api(project.dependencies.platform(libs.koin.bom))
                api(libs.koin.core)
                implementation(libs.room.runtime)
                implementation(libs.sqlite.bundled)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
        androidMain.dependencies {
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.ktor.client.okhttp)
        }
        val desktopMain by getting {
            dependencies {
                implementation(libs.ktor.client.okhttp)
            }
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

android {
    namespace = "com.goldenpaw.shared"
    compileSdk = 35
    defaultConfig {
        minSdk = 26
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

room {
    schemaDirectory("$projectDir/schemas")
}

dependencies {
    listOf("kspAndroid", "kspDesktop", "kspIosX64", "kspIosArm64", "kspIosSimulatorArm64").forEach {
        add(it, libs.room.compiler)
    }
}
